# NumPy

Numpy stands for Numerical Python. Numpy(Numerical Python) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with arrays. It contains the data structures needed for storing and accessing arrays. It has simple operations and functions for computation of arrays. In addition to numeric data types, NumPy can store other data types such as strings, boolean, and etc.


## NumPy Installation
It is possible to install numpy on Jupyter notebook or the command prompt using the following command.

```sh
pip install numpy
```

## Importing NumPy
Numpy can be imported as follows

If we want to use the numpy module without renaming we import it as follows.
```py
import numpy
```
It is common to rename the numpy module as np. To rename the name numpy to np we use the keyword *as* and the importing looks like as follows
```py
import numpy as np
```

In [244]:
# How ot import numpy
import numpy as np

In [245]:
# Let us import matplot.lib  and seaborn for data visualization
# installation of matplotlib and seaborn is required

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [246]:
## import stats for some statistical methods
from scipy import stats

## NumPy Version
Checking of the numPy version

In [247]:
# How check the version of numpy package
print('NumPy:', np.__version__)


NumPy: 1.19.2


## Creating of NumPy Arrays
We can change Python list and tuple to NumPy array.
Example of list and tuple:
```py
lst = [1, 2, 3, 4,5] # list
tpl = (1, 2, 3, 4, 5) # tuple
```

### Creating NumPy array from Python lists

In [248]:
# creating python list
lst = [1, 2, 3, 4, 5]
# Checking data types
print('Type : ', type(lst))
print(lst)

Type :  <class 'list'>
[1, 2, 3, 4, 5]


In [249]:
lst_of_lsts = [[0, 1, 2], [3,4,5],[6,7,8]]
print(lst_of_lsts)
print(type(lst_of_lsts))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'list'>


The numPy array has a *ndarry* data type which refers to n dimensional array. 

In [250]:
arr = np.array(lst)
print('Type:', type(arr))
print(arr)

Type: <class 'numpy.ndarray'>
[1 2 3 4 5]


In [251]:
two_dim_arr = np.array(lst_of_lsts)
print(two_dim_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Creating NumPy arrays with different data types
It is possible to create a numpy array with different data types with dtype 

### Creating integer NumPy array

In [252]:
# Python list
lst = [1,2,3,4,5]
print(lst)

arr_int = np.array(lst, dtype='int')
print(arr_int)
print(type(arr_int))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating floating number NumPy array

In [253]:
# Python list
lst = [1,2,3,4,5]
print(lst)

arr_float = np.array(python_list, dtype='float')
print(arr_float)
print(type(arr_float))

[1, 2, 3, 4, 5]
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


### Creating complex NumPy array


In [254]:
# Python list
lst = [1,2,3,4,5]
print(lst)

arr_complex = np.array(lst, dtype='complex')
print(arr_complex)
print(type(arr_complex))

[1, 2, 3, 4, 5]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
<class 'numpy.ndarray'>


### Creating String NumPy array

In [255]:
# Python list
lst = [1,2,3,4,5]
print(lst)
arr_str = np.array(lst, dtype='str')
print(arr_str)
print(type(arr_str))

[1, 2, 3, 4, 5]
['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [256]:
fruits = ['Apple','Avocado', 'Banana', 'Mango', 'Orange']
fruits_arr = np.array(fruits)
print(fruits_arr)

['Apple' 'Avocado' 'Banana' 'Mango' 'Orange']


### Creating Boolean NumPy Arrays
Creating a boolean a NumPy array from list

In [257]:
arr_bool = np.array([0, 1, -1, 0, 0], dtype=bool)
print(type(arr_bool))
print(arr_bool)

<class 'numpy.ndarray'>
[False  True  True False False]


*Summary of creating NumPy array with different data types*

In [258]:
np_int_arr = np.array([1,2,3,4,5.0], dtype = 'int')
np_float_arr = np.array([1,2,3,4,5.0], dtype = 'float')
np_bool_arr = np.array([-3, -2, -1, 0,2,3,4,5.0], dtype = 'bool')
np_complex_arr = np.array([1, 2,3,4,5.0], dtype = 'complex')
np_str_arr = np.array([1,2,3,4,5.0], dtype = 'str')

print(np_int_arr)
print(np_float_arr)
print(np_bool_arr)
print(np_complex_arr)
print(np_str_arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True False  True  True  True  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
['1' '2' '3' '4' '5.0']


Nested list can create multidimensional numPy arrays. It is possible to create a multidimensional array using Python list of lists

In [259]:
lst_of_lsts = [[0,1,2], [3,4,5], [6,7,8]]
two_dim_arr = np.array(lst_of_lsts)
print(two_dim_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### NumPy array attributes
The numPy array has different attributes that give more information about the array such as *ndim*, *shape*, *size*, *dtype*, *itemsize*
- ndim - returns the dimension of the numPy array
- shape - returns the number of rows and columns of a numPy array
- size - the total number of elements in the numPy array
- dtype - returns the data type of the numPy array 
- itemsize - returns the size in bytes of each elements in the numPy array

The NumPy *shape* method provide the shape of the array as a tuple. The first is the row and the second is the column. If the array is just one dimensional it returns the size of the array(n,).

In [260]:
arr = np.array([1, 2, 3, 4,5])
print('NumPy array dimension: ', arr.ndim)
print('NumPy array shape: ', arr.shape)
print('NumPy array size: ', arr.size)
print('NumPy array data type: ', arr.dtype)
print('NumPy array item size: ', arr.itemsize)

NumPy array dimension:  1
NumPy array shape:  1
NumPy array size:  5
NumPy array data type:  int32
NumPy array item size:  4


### Creating Multidimensional Array Using NumPy
We can create different dimension numPy array.

#### NumPy array without dimension or zero deminsion

In [261]:
ten = np.array(10)
print(ten)
print(f'The numPy n-d:{ten.ndim},shape:{ten.shape}, size:{ten.size}, date type:{ten.dtype}, itemsize:{ten.itemsize}') 

10
The numPy n-d:0,shape:(), size:1, date type:int32, itemsize:4


We can use simple function that provides information about the numPy array

In [262]:
def get_numpy_array_info(arr):
    print(f'The numPy n-d:{arr.ndim},shape:{arr.shape}, size:{arr.size}, date type:{arr.dtype}, itemsize:{arr.itemsize}')

#### One dimension numPy array
A list can create a one dimensional numPy array.


In [263]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(lst)
print(arr)
get_numpy_array_info(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
The numPy n-d:1,shape:(5,), size:5, date type:int32, itemsize:4


#### Two dimensional numPy array
A list of list can create a 2-d numPy array

In [271]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
two_dim_arr  = np.array(lst)
print(lst)
print(two_dim_arr)
get_numpy_array_info(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The numPy n-d:1,shape:(5,), size:5, date type:int32, itemsize:4


In [272]:
# 2 Dimension Array
two_dim_arr = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dim_arr))
print(two_dim_arr)
print('Dim:', two_dim_arr.ndim)
print('Shape: ', two_dim_arr.shape)
print('Size:', two_dim_arr.size)
print('Data type:', two_dim_arr.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dim: 2
Shape:  (3, 3)
Size: 9
Data type: int32


## Three dimensional numPy array
List of lists of list create a 3-d numPy array

In [291]:
lst = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
three_dim_arr = np.array(lst)
print(lst)
print(three_dim_arr)
get_numpy_array_info(two_dim_arr)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The numPy n-d:3,shape:(1, 3, 3), size:9, date type:int32, itemsize:4


## Converting NumPy array to list

In [292]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(arr)
lst = arr.tolist()
lst_of_lsts = two_dim_arr.tolist()
print(lst_of_lsts )

[1 2 3 4 5]
[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]


In [308]:
print(lst)
print(type(lst))

[1, 2, 3, 4, 5]
<class 'list'>


## Creating NumPy Array from Tuples

In [309]:
tpl = (1,2,3,4,5)
print(type(tpl))

<class 'tuple'>


In [310]:
arr = np.array(tpl)
print(type(arr))
print('numpy_array_from_tuple:',arr)

<class 'numpy.ndarray'>
numpy_array_from_tuple: [1 2 3 4 5]


In [311]:
print(two_dim_arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [312]:
print('She of numpy_two_dimensional_array: ', two_dim_arr.shape)

She of numpy_two_dimensional_array:  (1, 3, 3)


## Size of a NumPy array
In NumPy to know the number of items in a NumPy array list we use size

In [313]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

In [314]:
print('Size: ', arr.size)

Size:  5


In [315]:
print(np_two_dim_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [316]:
print('Size: ', np_two_dim_arr.size)

Size:  9


## Data Type of NumPy Array
Type of data types: str, int, float, complex, bool, list, None

In [317]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_arr = np.array(int_lists)
print(int_arr)
print(int_arr.dtype)
float_arr = np.array(int_lists, dtype=float)
print(float_arr)
print(float_arr.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


## Iterating NumPy Array

We can iterate through each elements of numPy array using loops. 


In [318]:
# 1-d array
arr = np.array([1, 2, 3, 4, 5])
print('Dim:', arr.ndim)
for item in arr:
    print(item)

Dim: 1
1
2
3
4
5


In [319]:
# 2-d array
arr = np.array([[1, 2], [3, 4], [5,6]])
print('Dim:', arr.ndim)
for item in arr:
    print(item)
    

for item in arr:
    for i in item:
        print(i)

Dim: 2
[1 2]
[3 4]
[5 6]
1
2
3
4
5
6


In [320]:
# 3-d array
arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print('Dim:', arr.ndim)
for item in arr:
    print(item)
    



Dim: 3
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


Iterating using ndenumerator method allow to access the element with the location of the specific element.

In [321]:
for x in np.ndenumerate(arr):
    print(x)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((0, 2, 0), 5)
((0, 2, 1), 6)
((1, 0, 0), 7)
((1, 0, 1), 8)
((1, 1, 0), 9)
((1, 1, 1), 10)
((1, 2, 0), 11)
((1, 2, 1), 12)


## Mathematical Operation Using NumPy
Numpy array is not like exactly like python list. To do mathematical operation in pyhton list we have to loop through the items but numpy can allow to do any mathematical operation without looping. Mathematical Operation:

- Addition (+)  
- Subtraction (-)  
- Multiplication (*)  
- Division (/)  
- Modules (%)  
- Floor Division(//)  
- Exponential(**)  

### Addition
Adding to scalar value is easy but add some value on a python list is not an easy operation. However, numPy array made it easy to do arithemtic operation without a use of any loops.

In [323]:
# Mathematical Operation
# Addition
arr = np.array([1, 2, 3, 4, 5])
print('original array: ',arr)
ten_plus_original = arr  + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


### Subtraction

In [325]:
# Subtraction
arr = np.array([1, 2, 3, 4, 5])
print('original array: ',arr)
ten_minus_original = arr  - 10
print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


###  Multiplication


In [326]:
arr = np.array([1, 2, 3, 4, 5])
print('original array: ', arr)
ten_times_original = arr * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


In [327]:
# let's  seee some use cases

x = np.array(range(0,50))
y = x * 2
print(x)
print(y)
plt.scatter(x,y, c='brown')
plt.title('X vs Y')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


### Division

In [336]:
# Division
arr = np.array([1, 2, 3, 4, 5])
print('original array: ', arr)
ten_times_original =arr  / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [337]:
### Modulus
# Modulus; Finding the remainder
arr = np.array([1, 2, 3, 4, 5])
print('original array: ',arr)
ten_times_original = arr % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


## Modulos

In [343]:
#modulous: the division result without the remainder
arr = np.array([1, 2, 3, 4, 5, 11])
print('original array: ', arr)
ten_times_original = arr // 10
print(ten_times_original)

original array:  [ 1  2  3  4  5 11]
[0 0 0 0 0 1]


### Floor Division

In [344]:
# Floor division: the division result without the remainder
arr = np.array([1, 2, 3, 4, 5, 11])
print('original array: ', arr)
ten_times_original = arr // 10
print(ten_times_original)

original array:  [ 1  2  3  4  5 11]
[0 0 0 0 0 1]


### Exponential

In [359]:
# Exponential is finding some number the power of another:
arr = np.array([1, 2, 3, 4, 5])
print('original array: ', arr)
ten_times_original = arr  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


## Converting Data Types
We can convert the data types of numpy array

### Converting Data Types from Int to Float

In [366]:
np_int_arr = np.array([1,2,3,4])
print(np_int_arr)

[1 2 3 4]


In [367]:
np_float_arr = np_int_arr.astype('float')

In [368]:
print(np_float_arr)

[1. 2. 3. 4.]


### Converting Data Types 


In [369]:
# to int
np_int_arr = np_float_arr.astype('int')

In [370]:
print(np_int_arr)

[1 2 3 4]


In [371]:
#to float

np_float_arr = np_int_arr.astype('float')
print(np_float_arr)

[1. 2. 3. 4.]


In [372]:
# Converting Data Types Int to Boolean
np_bool_arr = np.array([-3, -2, 0, 1,2,3]).astype('bool')
print(np_bool_arr)


[ True  True False  True  True  True]


In [373]:
# int to string
np_str_arr = np_int_arr.astype('str')
print(np_str_arr)

['1' '2' '3' '4']


## Getting items from a numpy array

In [374]:
# 2 Dimension Array
two_dim_arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dim_arr[0]
second_row = two_dim_arr[1]
third_row = two_dim_arr[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


In [375]:
first_column= two_dim_arr[:,0]
second_column = two_dim_arr[:,1]
third_column = two_dim_arr[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dim_arr)

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## NumPy array Indexing

Accessing one dimensional array elements is similar to accessing list elements. The first element can be accessed by index 0. See the example below. Negative indexing is also possible. The last element is at -1.

In [376]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])

1
5


Accessing two or more dimensional array elements is a bit different from accessing ordinary list. In order to access a 2-D array element, we use the numbers separated by a comma.
The first numbers reperesents the dimension and the second number refers to the index of the lement.Let's see an example.

In [377]:
# 2-D
lst_lst =[[1,2,3],[4,5,6],[7,8,9]]
two_dim_arr = np.array(lst_lst)
print(two_dim_arr)
print(two_dim_arr[0, 2])
print('dim:', two_dim_arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
dim: 2


In [378]:
# 3-D

lst_lst_lst = [[[1,2,3],[4,5,6],[7,8,9]]]
three_dim_arr = np.array(lst_lst_lst)
print(three_dim_arr)
print(three_dim_arr[0, 2, 2]) # the
print('dim:', three_dim_arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
dim: 3


## Slicing some parts of Numpy array
Slicing in numpy is similar to slicing in python list

In [379]:
# [start:end:step]
# [:] 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr[:])
print(arr[::])
print(arr[::2]) # 2 is a step
print(arr[0:3])
print(arr[3:])


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1 2 3]
[4 5]


In [380]:
# Gives the same numPy array
two_dim_arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(two_dim_arr[::])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [381]:
two_dim_arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
print('First row', two_dim_arr[0:2]) # slices the first two rows
print(two_dim_arr[0:3, 0]) # slices the first item in each column
first_two_rows_and_columns = two_dim_arr[0:3, 0:2]
print(two_dim_arr[:])
print(two_dim_arr)
print(first_two_rows_and_columns)
print(type(two_dim_arr))

First row [[1 2 3]
 [4 5 6]]
[1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
<class 'numpy.ndarray'>


In [382]:
two_dim_arr[2, 1:]

array([8, 9])

In [383]:
# Slicing out the middle four items
two_dim_arr_2= np.array([[1,2,3,7],[4,5,6, 15], [7,8,9,24],  [10,11,12, 33]])
two_dim_arr_2

array([[ 1,  2,  3,  7],
       [ 4,  5,  6, 15],
       [ 7,  8,  9, 24],
       [10, 11, 12, 33]])

In [384]:
two_dim_arr_2[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [385]:
# Assigning 
two_dim_arr_2[1:3, 1:3] = 25
two_dim_arr_2

array([[ 1,  2,  3,  7],
       [ 4, 25, 25, 15],
       [ 7, 25, 25, 24],
       [10, 11, 12, 33]])

## How to reverse the rows and the whole array?

In [386]:
two_dim_arr[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [387]:
two_dim_arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

## Reverse the row and column positions


In [388]:
two_dim_arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dim_arr[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [389]:
two_dim_arr[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [390]:
## How to represent missing values

In [391]:
print(two_dim_arr)
two_dim_arr[1,1] = 55
two_dim_arr[1,2] = 44
print(two_dim_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


### NumPy Zeros

In [392]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int)
numpy_zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Numpy ones


In [393]:
# Numpy ones
numpy_ones = np.ones((3,5),dtype=int,order='C')
print(numpy_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [394]:
twos = numpy_ones * 2

In [395]:
print(twos)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


### NumPy Full to create identical itmes


In [396]:
np_full = np.full((3, 5), fill_value=4)
print(np_full)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


### NumPy Eye

The eye function creates an identity matrix, that is, a matrix with elements on the diagonal are set to one, and non-diagonal elements are set to zero:

In [397]:
np_eye = np.eye(3, dtype=int)
print(np_eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [398]:
np_eye2 = np.eye(5, dtype=int)
print(np_eye2)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### NumPy Empty
The NumPy *empty* method returns a new array of given shape and type, with random values.

In [399]:
np.empty((2, 4))

array([[0., 0., 1., 0.],
       [0., 1., 1., 1.]])

In [400]:
np.empty((2, 2), dtype=int)

array([[1, 2],
       [3, 4]])

### Shape and Reshape a numPy array
The *shape* attribute provide the dimension of the numPy array. The reshape method takes arguments and reshape the array to a different dimension.

In [401]:
nums = np.arange(12)
nums.shape

(12,)

In [402]:
nums = np.arange(12)
print(nums)
new_arr = nums.reshape(3, 4)
print(new_arr)
print(new_arr.ndim) # 2-d
print(new_arr.shape) # 3 rows and 3 columns

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)


In [403]:
nums = np.arange(12)
print(nums)
new_arr = nums.reshape(3, 4)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Reshape

In [404]:

# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
print(first_shape.shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


## Flatten
The flaten method changes the numPy array to 1-dimensional array

In [405]:
flattened = reshaped.flatten()
print(flattened)
print('Shape:', flattened.shape, 'Dim:', flattened.ndim)


[1 2 3 4 5 6]
Shape: (6,) Dim: 1


In [406]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 2, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Concatenating Numpy arrays
By default the NumPy concatenate method joins the arrays along axis 0. To join the arrays horizontally, add parameter axis=1:

In [407]:
x = np.arange(2)
y = np.arange(2, 5)
z = np.concatenate((x, y))
print(z)

[0 1 2 3 4]


In [408]:
x = np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [412]:
# concant
print(np.concatenate((x, x), axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [413]:
# concant
print(np.concatenate((x, x), axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


### Joining with stack method
It is possible to join horizontally or vertically by changing the value of axis to 0 or 1. The default axis value is zero and that means a horizontal join.


In [421]:
 ## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])
print('concatenating list:', np_list_one + np_list_two)
print(np.stack((np_list_one, np_list_two))) # default axis value is zero.

concatenating list: [5 7 9]
[[1 2 3]
 [4 5 6]]


In [425]:
 ## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])
print( np_list_one + np_list_two)
print(np.stack((np_list_one, np_list_two), axis=1))

[5 7 9]
[[1 4]
 [2 5]
 [3 6]]


### Horizontal Stack

In [426]:
 ## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])
print(np_list_one + np_list_two)
print('Horizontal Append:\n', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append:
 [1 2 3 4 5 6]


### Vertical Stack

In [427]:
 ## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


## Generating Random Numbers

In [437]:
# Generating a random integers between 0 and 10 inclusive

random_int = np.random.randint(0, 11)
random_int

0

In [438]:
# Generate a random float  number between 0 and 0.999..
random_float = np.random.random()
print(random_float)

0.4099787844112669


In [439]:
 # Generate a random numpy array of float  numbers
random_floats = np.random.random(5)
print(random_floats)

[0.22587659 0.0188218  0.1005489  0.22376462 0.86790537]


In [441]:
# Random numbers between [0,1) of shape 2,3
np_random_nums = np.random.random(size=(2, 3))
print(np_random_nums)


[[0.16948871 0.58021159 0.4058133 ]
 [0.15162521 0.42037159 0.52096055]]


In [443]:
np_random_nums.shape
np_random_nums.flatten()

array([0.16948871, 0.58021159, 0.4058133 , 0.15162521, 0.42037159,
       0.52096055])

In [444]:
## Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

array([[0.12099852, 0.05660326],
       [0.69331399, 0.8406786 ]])

In [449]:
 # Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size= 4)
random_int

array([2, 8, 2, 5])

In [451]:
 # Generating a random integers between 2 and 11, and creating 2-dim array
random_ints = np.random.randint(2,10, size=(2,4))
random_ints

array([[9, 9, 3, 5],
       [3, 4, 2, 3]])

In [452]:
# Generating a random integers between 0 and 10, [0, 10)
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[7, 5, 9],
       [8, 5, 7],
       [3, 6, 3]])

In [453]:
# Generating a random integers between 0 and 10, [0, 10)
random_int = np.random.randint(2,10,(3,3))
random_int

array([[8, 2, 7],
       [6, 2, 7],
       [3, 8, 9]])

In [457]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=3))

['u' 'u' 'i']


In [459]:
print(np.random.choice(list('Python'), size=5))

['h' 't' 'y' 'o' 'y']


In [462]:
random_id = np.random.choice(list('abcdefghijklmnopkrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'), size=24).tolist()
random_id = ''.join(random_id)
print(random_id)
print(len(random_id))

nNa3RMvCtyIebVkbmEy7lkKG
24


In [468]:
def generate_random_id(n = 12):
    random_id = np.random.choice(list('abcdefghijklmnopkrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'), size = n).tolist()
    random_id = ''.join(random_id)
    return random_id

print(generate_random_id())
print(generate_random_id(6))
print(generate_random_id(24))

CJGmWahaGYgC
Stg3zm
eSoiGdkz1wPgeyQ7MOBV6wWU


### Generating random data

In [472]:
# first argument min, second argument max and third argument is size
s = np.random.uniform(-1, 0, 1000)
print(np.all(s <= 0))
print(s)

True
[-9.09125352e-03 -8.40358293e-01 -8.79495448e-01 -9.44144541e-02
 -2.27699460e-01 -5.23188528e-01 -3.27116558e-01 -9.61947088e-01
 -3.68652591e-01 -6.84148999e-01 -6.39685163e-03 -6.76768498e-02
 -2.18129853e-01 -9.01380247e-01 -4.24606130e-01 -4.14084199e-01
 -1.69767803e-01 -7.83344411e-01 -6.37814720e-02 -5.92400457e-01
 -7.12388759e-01 -9.41375494e-01 -7.17421556e-01 -1.14963817e-01
 -8.43083349e-01 -3.90743028e-01 -4.92756774e-01 -7.97481607e-01
 -9.52791541e-01 -7.10127285e-01 -8.43260962e-01 -3.12651822e-01
 -5.68688931e-02 -2.91650420e-02 -1.36216117e-01 -4.60461495e-01
 -6.76362399e-01 -5.08259844e-01 -7.15531881e-01 -3.11324087e-01
 -6.02793104e-01 -3.70027385e-02 -3.79979242e-01 -2.59870216e-01
 -4.36218322e-02 -7.63578896e-01 -6.47027340e-03 -3.79266317e-01
 -4.04224549e-03 -3.44907121e-01 -3.57242331e-01 -9.21954753e-01
 -7.44045315e-02 -8.45647078e-01 -7.80209001e-01 -9.07885277e-01
 -9.83812403e-01 -7.05245358e-02 -7.38523741e-01 -4.89655720e-01
 -5.65514888e-01 -3.

In [475]:
count, bins, ignored = plt.hist(s, 10, density=True)
plt.plot(bins, np.ones_like(bins), linewidth=2, color='r')
plt.show()

In [476]:
# np.random.normal(mu, sigma, size)
# mu - mean, sigma - sigma -standard deviation, size - number of obsevations
normal_array = np.random.normal(79, 15, 10000)
normal_array

array([68.80039957, 57.06427274, 90.00446115, ..., 84.40814004,
       57.12822484, 87.91751196])

In [480]:
plt.hist(normal_array,bins=50, color='lightgreen', density=True)
plt.show()

### Maintaining the same generated data

Sometimes we would not like to generate a new set of data instead we would like to keep what we created. To keep the created data we can use the *seed* method.

In [110]:
np.random.seed(0)
integers = np.random.randint(0, 10, 21)
print(integers)


[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5]


In [111]:
data = np.random.normal(0, 2, 30)
print(data)

[-0.94154201  1.94603199 -2.55629824  2.87474136 -0.15540913  2.17926033
  0.19308534  2.83733422  2.33654627  1.89437189  2.17097407  4.7644489
 -0.81204747  0.53289068 -2.71142745 -0.22820506 -1.68846173  1.41128162
 -0.79757235 -1.65439307 -0.8314894  -1.04902439  1.62620254 -0.45850126
  4.32343475 -1.91386286  0.13462166  0.41299767 -0.91376265 -2.11995153]


In [112]:
generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
generator.randint(0, 10, 21)

array([2, 2, 6, 1, 3, 9, 6, 1, 0, 1, 9, 0, 0, 9, 3, 4, 0, 0, 4, 1, 7])

## Matrix in NumPy

In [113]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))

In [114]:
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

In [116]:
A = four_by_four_matrix * 2
B = four_by_four_matrix * 4
print(A)
print(B)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [4. 4. 4. 4.]
 [2. 2. 2. 2.]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]
 [4. 4. 4. 4.]]


In [117]:
A_plus_B = A + B
print(A_plus_B)

[[ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]
 [12. 12. 12. 12.]
 [ 6.  6.  6.  6.]]


In [118]:
A_minus_B = A - B
print(A_minus_B)

[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-4. -4. -4. -4.]
 [-2. -2. -2. -2.]]


In [119]:
A_times_B = A - B
print(A_times_B)

[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-4. -4. -4. -4.]
 [-2. -2. -2. -2.]]


In [120]:
np.transpose(A_times_B)

matrix([[-2., -2., -4., -2.],
        [-2., -2., -4., -2.],
        [-2., -2., -4., -2.],
        [-2., -2., -4., -2.]])

### Numpy numpy.arange()

#### What is arrange?
Sometimes, you want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function

In [121]:
# creating list using range(starting, stop, step)
lst = range(0, 11, 2)
lst

range(0, 11, 2)

In [122]:
for l in lst:
    print(l)

0
2
4
6
8
10


In [123]:
# Similar to range arange numpy.arange(start, stop, step)
whole_numbers = np.arange(0, 20, 1)
whole_numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [124]:
natural_numbers = np.arange(1, 20, 1)
natural_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [125]:
odd_numbers = np.arange(1, 20, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [126]:
even_numbers = np.arange(2, 20, 2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### Creating sequence of numbers using linspace

In [127]:
# numpy.linspace(start, end, size, endpoint) the end is included by default
# numpy.logspace() in Python with Example
# For instance, it can be used to create 10 values from 1 to 5 evenly spaced.
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [128]:
# not to include the last value in the interval
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [129]:
x = np.linspace(-10, 10, num=50)
y = 2 * x  + 2
plt.scatter(x, y)
plt.show()

In [130]:
x = np.linspace(-10, 10, num=50)
y = x ** 2
plt.scatter(x, y)
plt.show()

In [131]:
x = np.linspace(-10, 10, num=50)
y = x ** 2 - 25
plt.scatter(x, y)
plt.show()

In [132]:
x = np.linspace(-10, 10, num=50)
y = -x ** 2 + 25
plt.scatter(x, y)
plt.show()

In [133]:
# LogSpace
# LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.


In [134]:
# Syntax:

# numpy.logspace(start, stop, num, endpoint)

np.logspace(2, 4.0, num=4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [135]:
# to check the size of an array
x = np.array([1,2,3], dtype=np.complex128)

In [136]:
x

array([1.+0.j, 2.+0.j, 3.+0.j])

In [137]:
x.itemsize

16

## NumPy Statistical Functions with Example
NumPy has quite useful statistical functions for finding minimum, maximum, mean, median, percentile,standard deviation and variance, etc from the given elements in the array. The functions are explained as follows − Statistical function Numpy is equipped with the robust statistical function as listed below

Numpy Functions
- Min np.min()
- Max np.max()
- Percentile(25, 50, 75) using np.percentile(arr, 25)
- Mean np.mean()
- Median np.median()
- Varience np.var(data)
- Percentile
- Standard deviation np.std()

stats.mode(data)  

## Using Numpy to calculate statistical measures
It is easy to calcualte the statistical measures such as mean, median, standard deviation, varience etc 
# A set of age of students in python class

data = [19, 20, 22, 33, 45, 60, 25, 24, 40, 20, 15, 22, 24, 26, 26, 28, 27, 24, 35, 40, 40, 24, 38, 40, 28, 23] 

In [138]:
np.random.random()

0.7506861412184562

In [139]:
np.random.random(3)

array([0.60783067, 0.32504723, 0.03842543])

In [140]:
np.random.randint(5, 10, (3, 4)) # does not inlcued the last value [5, 10)

array([[8, 9, 9, 9],
       [8, 9, 9, 9],
       [5, 9, 8, 7]])

In [141]:
np.random.normal(0, 2, 5)

array([-1.79093312,  0.773805  , -1.02161028, -2.36126437, -0.05636446])

In [142]:
np.random.normal(0, 2, (3, 4)) # mean = 0, stdev = 2, 3 x 4 array

array([[ 0.85666374,  0.13303444,  0.6049438 , -1.26864419],
       [-0.72548233, -1.3449209 , -0.71910632, -1.62629256],
       [-3.4525652 ,  0.35485228, -0.80356187, -3.26039669]])

In [143]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis
## min, max, mean, median, sd
print('min: ', two_dim_arr.min())
print('max: ', two_dim_arr.max())
print('25th percentile', np.percentile(two_dim_arr, 25))
print('50th percentile', np.percentile(two_dim_arr, 50))
print('75th percentile', np.percentile(two_dim_arr, 75))
print('mean: ',round(two_dim_arr.mean(), 2))
print('mode: ', stats.mode(two_dim_arr)) # numpy has no mode method
print('median: ', np.median(two_dim_arr))
print('sd: ', round(two_dim_arr.std(), 2))

min:  1
max:  55
25th percentile 3.0
50th percentile 7.0
75th percentile 9.0
mean:  14.78
mode:  ModeResult(mode=array([[1, 2, 3]]), count=array([[1, 1, 1]]))
median:  7.0
sd:  18.91


In [144]:
print(two_dim_arr)
print('Column with minimum: ', np.amin(two_dim_arr, axis=0))
print('Column with maximum: ', np.amax(two_dim_arr, axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dim_arr, axis=1))
print('Row with maximum: ', np.amax(two_dim_arr, axis=1))

[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]
Column with minimum:  [1 2 3]
Column with maximum:  [ 7 55 44]
=== Row ==
Row with minimum:  [1 4 7]
Row with maximum:  [ 3 55  9]


## How to create repeating sequences?

In [145]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 3))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 3))

Tile:    [1 2 3 1 2 3 1 2 3]
Repeat:  [1 1 1 2 2 2 3 3 3]


In [146]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 1000) # mean, standard deviation, number of samples
np_normal_dis
## min, max, mean, median, sd
print('min: ', np.min(np_normal_dis))
print('max: ', np.max(np_normal_dis))
print('mean: ', np.mean(np_normal_dis))
print('median: ', np.median(np_normal_dis))
print('mode: ', stats.mode(np_normal_dis))
print('sd: ', np.std(np_normal_dis))

min:  3.4769284726000365
max:  6.58548738664509
mean:  4.9757236255377535
median:  4.974828091188378
mode:  ModeResult(mode=array([3.47692847]), count=array([1]))
sd:  0.4859817987330746


In [147]:
plt.hist(np_normal_dis, color="grey", bins=30)
plt.show()

In [148]:
x  = np.random.normal(28, 15, 100000)
ax = sns.histplot(x, kde=True, linewidth=0)
ax.set(xlabel='x', ylabel='y', title='X vs Y')
plt.show()

## Linear Algebra

In [149]:
# numpy.dot(): Dot Product in Python using Numpy
# Dot Product
# Numpy is powerful library for matrices computation. For instance, you can compute the dot product with np.dot

# Syntax

# numpy.dot(x, y, out=None)

### Dot Product

In [150]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])
### 1*4+2*5 + 3*3
np.dot(f, g)  # 23

23

### NumPy Matrix Multiplication with np.matmul()

In [151]:
### Matmul: matruc product of two arrays
h = np.array([[1,2],[3,4]])
i = np.array([[5,6],[7,8]])
### 1*5+2*7 = 19
print(h)
print(i)
np.matmul(h, i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [152]:
## Determinant 2*2 matrix
### 5*8-7*6np.linalg.det(i)

In [153]:
np.linalg.det(i)

-1.999999999999999

In [154]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1

In [155]:
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])